workflows:
  alpine_printpack_macos:
    name: Alpine Printpack macOS Build
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Enable macOS
        script: |
          flutter config --enable-macos-desktop

      - name: Build macOS Release
        script: |
          flutter build macos --release

    artifacts:
      - build/macos/Build/Products/Release/*.app

    publishing:
      email:
        recipients:
          - yashrochlani7@gmail.com
