workflows:
  alpine_printpack_android:
    name: Alpine Printpack Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_PACKAGE: "com.example.costingapp"
    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Build Android APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - yashrochlani7@gmail.com
